version: '3.7'
services:
  minio:
    image: minio/minio:latest
    container_name: experiments_minio
    restart: always
    ports:
      - '9090:9000'
      - '9091:9001'
    environment:
      - MINIO_ROOT_USER=ADMIN
      - MINIO_ROOT_PASSWORD=senhadificil
    command: server --address ":9000" --console-address ":9001" /data
    volumes:
      - ~/minio/data:/data